### ISSUE TITLE
snap - `wix-ui-core` Build Error

### ISSUE THREAD

**Issue by hepiyellow** [wix-incubator/ui-autotools#242]
This build fails on `autotools-snap`:

- [Failing build](http://pullrequest-tc.dev.wixpress.com/viewLog.html?buildId=2486413&buildTypeId=FedInfra_Package_WixUi)

With error:
```
 [ Error: failed to render screenshot d6fce0de-a888-4865-94f8-c994d1bb8c9d
       at getRenderStatusJob (/home/builduser/agent00/work/188f76a73d1e1ff0/packages/wix-ui-core/node_modules/@applitools/visual-grid-client/src/sdk/waitForRenderedStatus.js:25:25)
       at getRenderStatusJob (/home/builduser/agent00/work/188f76a73d1e1ff0/packages/wix-ui-core/node_modules/@applitools/visual-grid-client/src/sdk/waitForRenderedStatus.js:32:18)
       at process._tickCallback (internal/process/next_tick.js:68:7) ]
```

- [Another build failure without any changes](http://pullrequest-tc.dev.wixpress.com/viewLog.html?buildId=2486621&buildTypeId=FedInfra_Package_WixUi&tab=buildLog#_state=1208)

This build also shows this error:
```
 [ Error: connect ETIMEDOUT 104.196.248.157:443
   at sendRequest (/home/builduser/agent00/work/188f76a73d1e1ff0/packages/wix-ui-core/node_modules/@applitools/eyes-sdk-core/lib/server/ServerConnector.js:92:11)
   at process._tickCallback (internal/process/next_tick.js:68:7) ]
```

**Does this mean that Applitools VisualGrid is flaky?**

@JoMarton @alisey @shlomitc

**Comment by hepiyellow** [comment]
@alisey

**Comment by hepiyellow** [comment]
happened again:
http://pullrequest-tc.dev.wixpress.com/viewLog.html?buildId=2486413&buildTypeId=FedInfra_Package_WixUi&tab=buildLog&_focus=6102#_state=1206
